### ISSUE TITLE
swoole版的xdebug?

### ISSUE THREAD

**Issue by mangowong** [mabu233/old_sdebug#1]
请问下这个debug工具适用于协程版的swoole吗，用法和xdebug基本一致吗

**Comment by mabu233** [comment]
只有基本的断点，查看变量值功能，而且不稳定😅

**Comment by mabu233** [comment]
你需要什么功能？

**Comment by mangowong** [comment]
> 你需要什么功能？

对于我而言，断点功能也基本够用。

**Comment by mabu233** [comment]
emmmm,其实我觉得断点好像没什么用,var_dump或者肉眼看就够了,可能我没接触的复杂项目吧。。
